### ISSUE TITLE
Windows VRDataIndex throws Assertion (String iterator not decrementable)

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#101]
On line 589 in VRDataIndex.cpp:

```c++
    // March backward to the first '/' (if there was one).
    while (((*(--it)) != '/') && (charLimit < fullName.length())) { charLimit++; };
```

Not sure what the problem is, but it looks like it will need to be fixed for debugging in windows.

**Comment by tsgouros** [comment]
This is silly, since the standard says iterators are supposed to be reversible. Works on Mac and Linux, what's Microsoft's problem? Oh, right, I remember. Never mind. I changed this to use a reverse iterator, but someone else will have to test under Windows for me. Use 'make test' and close this if it works.

**Comment by tsgouros** [comment]
Changed this back to Dan O for testing and seeing if the fix actually worked.

**Comment by dtorban** [comment]
Great!  Thanks, I'll try it out soon.

Thanks,
Dan

**Comment by tsgouros** [comment]
This works, right? Can you close?

**Comment by dtorban** [comment]
This looks great.  Thanks Tom!
