### ISSUE TITLE
install location for config files

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#108]
Subject of 2/10 meeting: config files should have a default install location. Agreed but I wonder if the plugins directory should be moved, too.

Right now, the installation defaults look like this, for a given install directory:

$install/bin 
$install/lib
$install/include
$install/plugins

Propose we change this to:

$install/bin
$install/lib
$install/include
$install/share/MinVR/plugins
$install/share/MinVR/config

This is a widely used standard on Linux and works fine on Mac, too. No idea if it matters for Win. Leaves room for $install/share/MinVR/doc and $install/share/MinVR/etc and whatever else should go in there.

**Comment by dankeefe** [comment]
When looking for a config file, try first in $MINVR_ROOT.  So, $install would be replaced by $MINVR_ROOT here.

**Comment by dtorban** [comment]
Checkout #78 for plugin search path

**Comment by dankeefe** [comment]
We should consider Windows and OSX in this discussion as well.  It would be nice if the way we handle different architectures can be as similar as possible.

We also need to think about having multiple versions of the library installed.  On a big shared system like the YURT or a CAVE where many people are working on the same filesystem, it will be important to support having multiple versions of the software work / installed at the same time on the system.

With this in mind, I would suggest that we include a version number in the recommended INSTALL_PREFIX as in the examples below.  In this case, all of the config and plugin files etc. will already be inside a MinVR-*version* directory and so I think that the share/MinVR subdirs are not needed.

------ Linux ------

Recommended/default INSTALL_PREFIX = /usr/local/libMinVR-*version*

Example file locations:
${INSTALL_PREFIX}/lib/libMinVR.so
${INSTALL_PREFIX}/lib/libMinVRd.so
${INSTALL_PREFIX}/plugins/libMinVR_OpenGL.so
${INSTALL_PREFIX}/plugins/libMinVR_OpenGLd.so
${INSTALL_PREFIX}/config/desktop-display.xml
${INSTALL_PREFIX}/include/api/MinVR.h
${INSTALL_PREFIX}/bin/itest-opengl-shaderpipeline


------ OSX ------

Recommended/default INSTALL_PREFIX = /Applications/libMinVR-*version*

Example file locations:
${INSTALL_PREFIX}/lib/libMinVR.dynlib
${INSTALL_PREFIX}/lib/libMinVRd.dynlib
${INSTALL_PREFIX}/plugins/libMinVR_OpenGL.dynlib
${INSTALL_PREFIX}/plugins/libMinVR_OpenGLd.dynlib
${INSTALL_PREFIX}/config/desktop-display.xml
${INSTALL_PREFIX}/include/api/MinVR.h
${INSTALL_PREFIX}/bin/itest-opengl-shaderpipeline

------ Windows ------

Recommended/default INSTALL_PREFIX = %Program Files%/MinVR-*version*

Example file locations:

${INSTALL_PREFIX}/bin/MinVR.dll  (.dlls go in /bin not /lib)
${INSTALL_PREFIX}/bin/MinVRd.dll
${INSTALL_PREFIX}/plugins/MinVR_OpenGL.dll
${INSTALL_PREFIX}/plugins/libMinVR_OpenGLd.dll
${INSTALL_PREFIX}/config/desktop-display.xml
${INSTALL_PREFIX}/include/api/MinVR.h
${INSTALL_PREFIX}/bin/itest-opengl-shaderpipeline.exe

**Comment by tsgouros** [comment]
Does the cmake install option include a way to create the links or Apple frameworks that users will need to use these libraries if they are installed in unusual places? I mean linking from /usr/local/lib to /usr/local/libMinVR-1.0/lib?

I'm ok with this, if it includes creating those things, through cmake or some other way. Also, not everyone who uses a Mac uses XCode. Some of us just treat them like linux boxes and compile with gcc.

**Comment by dankeefe** [comment]
I think something like that would be possible.  Searching around a bit, it looks like you can do something along these lines to create symlinks to installed targets if you want.  

SET(mylink /usr/local/lib/libMinVR.so)
SET(myfile ${CMAKE_INSTALL_PREFIX}/libMinVR.so)
ADD_CUSTOM_COMMAND( OUTPUT ${mylink}
                     COMMAND ln -s ${myfile} ${mylink}
                     DEPENDS install ${mylink} 
                     COMMENT "Adding link to ${mylink}")
ADD_CUSTOM_TARGET( install_minvr DEPENDS ${mylink})

But, is installing as a system-style library the right thing to do for MinVR?  

I would expect that most users will be on machines where they don't have root access and install MinVR in their local user directory rather than /usr/local.  

Other users may have root access.  For a lab like at the YURT, I could see that it might be useful to install in /usr/local, but I would think this is the situation where it's also likely that several versions of MinVR need to be installed on the same machine.  So, although less convenient initially, it might be more robust in terms of keeping old projects running over time, etc. to require users to include a -L flag in their compile/link options to specify the correct version of MinVR to load rather than having them point to a system-installed version that may change to link to a new version of MinVR every couple of months.

**Comment by tsgouros** [comment]
This should probably be closed. Not sure all the issues have been addressed, but we can reopen as needed.
