### ISSUE TITLE
Fake tracker bombs

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#130]
When I try to use the fake tracking node with a FreeGLUT plugin, I get this error. Using the Fake1 and Fake2 elements verbatim from the config file in 3DUI.

libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: map::at:  key not found

**Comment by dankeefe** [comment]
I'm not setup to easily test with FreeGlut, but I think it's an issue of
standardizing the events that are generated by the windows.  The
FakeTrackers expect a NormalizedPosition data field to the Mouse_Move
event.  Could you please this around line 100 of VRFreeGLUTInputDevice.cpp
so that it matches what is in the GLFW version?


void VRFreeGLUTInputDevice::cursorPositionCallback(int xpos, int ypos, bool
isActive) {
  std::string event = "Mouse_Move";
  _dataIndex.addData(event + "/XPos", xpos);
  _dataIndex.addData(event + "/YPos", ypos);
  _dataIndex.addData(event + "/Active", isActive);

  std::vector<float> pos;
  pos.push_back(xpos);
  pos.push_back(ypos);
  _dataIndex.addData(event + "/Position", pos);

  int width = glutGet(GLUT_WINDOW_WIDTH);
  int height = glutGet(GLUT_WINDOW_HEIGHT);
  pos[0] /= (float)width;
  pos[1] /= (float)height;
  _dataIndex.addData(event + "/NormalizedPosition", pos);
}




---
Daniel Keefe
Associate Professor
Department of Computer Science and Engineering
University of Minnesota
http://www.cs.umn.edu/~keefe/

**Comment by tsgouros** [comment]
Addressed by pull request #174
