### ISSUE TITLE
need better selectByAttribute()

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#149]
The VRDataIndex::selectByAttribute() method is now being asked to return *all* the names of objects with matching attributes in a container or in the containers it nests inside. But then there's a question of priority: which one do you want?  

The selectByAttribute() method returns a list of matching names, and the VRMain code simple uses the first one, assuming that it's the desired one. Returning a list is the functionality I need to implement the linking within the data index, but it seems excessive for the use it's being put to in VRMain. I propose a new function: selectFirstByAttribute, that simply returns a *single* name for the first value that matches the given attribute, starting from the current namespace/scope and working its way up the name hierarchy. That is what you want, right?

Assigning this to DanK so he sees it and he can assign it back to me.

**Comment by dankeefe** [comment]
Thanks Tom.  I'll add a couple of thoughts here...  I think this depends in part on the larger re-organization you are working on for the data index.  

1. For config files:  Attributes are used pretty extensively in the current config file format, so this is important to support unless we change that config file format extensively.  I think my expectation as a user would be that the scoping and inheritance should work the same way by default for all functions:  getValue(), getNames(), getNamesByAttribute(), etc..   So, if the default is to use inheritance, then I would expect it to be the default for all functions.  And, if a way to override that default is needed, then I would expect the override to work the same way for all functions.  For example, one way would be to pass a bool to each function (e.g., useLocalScopeOnly=true) to override the default use of inheritance.  Another way would be to have a separate set of functions (e.g., getValueInLocalScope(), getNamesInLocalScope(), getNamesByAttributeInLocalScope()).  I would try to think of them in pairs.

If I understand the code now, I think what it's doing now is more like getNamesByAttributeInAllScopes().  Is that important functionality to preserve?  I'm not sure what the use case would be for that.


2. BUT, in the bigger picture, for events/rendering:  If part of the goal of your current refactoring is to bring data index more in line with a lightweight, fast structure that would be useful for storing small event and render data, then I think it's important to simplify rather than extend with additional functions, and I would say that attributes aren't even needed there and are not worth additional overhead in serialization, usability, etc.  I keep coming back to the idea that it might make sense to use the same underlying infrastructure of the datums, flat map<> for storing them, etc that you have implemented in the underlying code, but split the functionality up into: 1. a config oriented, DataIndex, class that supports XML serialization, attributes, and fancier things, and 2. a lighter weight, DataSomething, class with binary serialization, no need for attributes, ...

**Comment by tsgouros** [comment]
The select from everywhere with an attribute is important internally to the implementation of the data index.

The naming inheritance works by giving you the first match of the name you ask for. If you want the attribute search to work the same way, it should do the same thing. The inheritance implies a ranking: you want the lowest value in the tree that satisfies. I could give you a list of all of them instead, but then your code would have to sort through the results and figure out for itself how it wants the inheritance to work and that doesn't seem like a good idea to me. 

The VRMain code currently uses two different selection paradigms.  First it wants all and only the direct children of a container (VRMain.cpp:453 on the beta branch. The code does not currently select only the direct children, but this results in some nodes being created multiple times, because the code gets RootNode/LookAt/Projection when it selects within RootNode, and then again when it selects within RootNode/LookAt. I have removed the redundancy by making the selection more precise.) and then it also uses the select-from-everywhere, form (VRMain.cpp:459), but only takes the first one. This only worked because of an oversight of mine, and also because no one tested VRMain on a config file with multiple satisfying entries. Or if they did test it, they got lucky, because the first element of the list is pretty random.

You keep coming back to that idea of a flat form, but we have talked about it before.  Again, the VRDatum objects *are* in a single map. The attributes are stored in the VRDatum objects, with the value itself. If you ignore the hierarchy -- which is easier in the revamped version now available -- it can't get any flatter. I could remove features for an event-biased data index, but the performance won't change for removing features that aren't being used and I'm not sure how having two versions of the data index and two different species of VRDatum objects would make anything simpler.

 -Tom

**Comment by tsgouros** [comment]
This is addressed in pull request #151. There are now three options for selection by attributes:

 1. Select everything at any level within a container that has an attribute of the given value (or any value if you use * as a wildcard.

 2. Select everything that is a child of a container. i.e. not grandchildren or great-grandchildren, etc. Use this for recursive processes.

 3. Select the first value with the given attribute, searching up from the given name space.
