### ISSUE TITLE
load default.minvr if no config is specified

### ISSUE THREAD

**Issue by dankeefe** [ivlab/MinVR2#183]
A feature that I had made possible in the past seems to no longer work.  In the past, it was possible to run a MinVR app with no command line arguments, and when it detected that no config file was specified it would load the default installed config file (default.minvr).  This is quite useful when developing in an IDE because you can run your program in debugging mode without having to re-setup command line arguments every time you regen the project file with cmake.  It's also nice for new users to be able to run the first app they build just by double-clicking it or starting it without any args.  @tsgouros -- I wonder if your changes to the command line parsing inadvertently broke this feature.

**Comment by tsgouros** [comment]
I probably broke this inadvertently, my apologies, but I also think that without better error messages from bad config files that this is actually not a helpful feature except for insiders. The default minvr config file gives me this error:

`Warning: Nothing in the factory catalog with the correct type: N5MinVR15VRWindowToolkitE
This is usually caused by a typo in your config file.`

This is not a typo in my config file, but is caused by the fact that I did not build the glfw plugin.
