### ISSUE TITLE
callback design : VREvent vs name and VRDataIndex

### ISSUE THREAD

**Issue by BenKnorlein** [ivlab/MinVR2#20]
I wanted to start discussing about the pros and cons for different callback designs. Dan, please feel free to attach  your document with different designs and ideas. The basic question for me is 

```
void callback(VREvent * event)
```

or

```
void callback(string name, VRDataIndex dataIndex)
```

I am a strong defender of the first example, but would still like to discuss. Maybe other designs are better.

Here are a number of reason why i prefer the first method:
If we use a class VREvent, which consists of basically a name and a VRDataIndex i see several advantages. Basically there is not much of a difference but maybe the following makes my ideas more clear:
- Both the name and dataIndex belong together, so there should be no way that they can be separated. They both belong to the same event.
- It fits to standard UI event processing where the event has a name or type and data
- It simplifies processing or deletion as there is only 1 object which has to be taken care of
- The event can be have derived classes, e.g. a VRJoystickEvent, which provides methods to access the data in the VRDataIndex in a more convenient way. (This again also is inline with standard UIs, e.g. MouseEvent ).This will also bring more advantages for later modules (see below). Note: That this are only methods to access the VRDataIndex (in case it follows a default naming convention), so this does not go against the ideas of the basic flexibility.

Here an idea why the possiblity to derive classes might be interesting: 
Imagine there is a high-level module for a Joystick. The design of the joystick should be similar to a button in a traditional UI. This means when the Joystick is created, the Joystick registers its callback automatically. When the Joystick receives a VREvent which was assigned to him, the joystick can cast it as a VRJoystickEvent and run its own callback. This would allow a user to create a Joystick and register a callback with it in which he receives a VRJoystickEvent. In this case he would not have to deal with the name of the event or the VRDataIndex which would give the developer a nice interface. (Note: which events to handle could be defined when constructing, or the high-level module could also handle the input)

**Comment by dankeefe** [comment]
Here are the examples for the eventCallback spec that I shared on Skype this morning:

``` C++

// Idea 1
// In this idea, VREvent is simply a (name, dataIndex) pair wrapped in a class called VREvent,
// and dataIndex is a "smallish" VRDataIndex that holds data for this event only.
void myEventCallback(VREvent e) {
  if (e.getName() == “Wand_Move”) {
    VRMatrix4 transform = e.getDataIndex()->getData(“Transform”);
  }
}


// What if we were to ditch VREvent?:

// Idea 2
void myEventCallback(std::string eventName, VRDataIndex eventData) {
  if (eventName == “Wand_Move”) {
    VRMatrix4 transform = eventData.getValue(“/Wand_Move/Transform”);
  }
}

// Idea 2 variants based on what exactly this VRDataIndex should hold:
//    A: as in Idea 1, it would hold only the data for the current event, e.g., only the data relevant to "Wand_Move"
//    B: all the events generated since the past frame, i.e., all the data that VRMain will have just requested from input devices and synched over the network
//    C: all the events processed so far this frame, i.e., something like the history or state of what has been processed so far
//    D: all the events processed so far during the execution of the whole program, not just this frame
//    E: values for everything in MinVR that uses a VRDataIndex (event data, config options, etc.), i.e., the idea of doing everything with one big global VRDataIndex



// Idea 3
// If we like 2A, then I propose that there is no need to include the prefix "/Wand_Move" when calling getValue()
void myEventCallback(std::string eventName, VRDataIndex eventData) {
  if (eventName == “Wand_Move”) {
    VRMatrix4 transform = eventData.getValue(“Transform”);
  }
}

// Idea 4
// If we like 2A, then another option in this style might be to pass a VRDataCollection, then it does not matter so much
// what is in the underlying VRDataIndex.
void myEventCallback(std::string eventName, VRDataCollection eventData) {
  if (eventName == “Wand_Move”) {
    VRMatrix4 transform = eventData.getValue(“Transform”);
  }
}


// Idea 5
// If we like idea 2E, then DataIndex is like a global variable, so we wouldn't even need to pass it to the callback
void myEventCallback(std::string eventName) {
  if (eventName == “Wand_Move”) {
    VRMatrix4 transform = VRMain::GlobalDataIndex->getValue(“\Wand_Move\Transform”);
  }
}
```

**Comment by tsgouros** [comment]
So I sat down this evening to make an event class that used the received index data as input to its constructor. And realized that Ben's idea of having a specialized event subclass could not work because how do you choose which constructor to use before reading the data? And if you have to read the data first to find out what's in it, then what's the point of the event object?

More detail: the client receives a lump of data, what does it do with that lump? 
- My version: inspect the lump to find out what's in it, act accordingly. Feed it to the eventCallback, see what happens.
- Ben's version: inspect the lump of data to figure out which kind of event it is, pack it into the appropriate event object which will do something, feed it to the eventCallback, etc.

Ok, fine. But the reason Ben's version seemed like a better idea to me this morning is that you could specialize the event object and add methods to it. But you can't know what constructor to feed the data to until you have inspected the lump of data, so as a strategy to avoid a long if statement, this will only work if you don't have specialized event objects. But if you don't have them, why bother with the event object at all?

So my question remains: what good is an event object instantiated as a C++ class as opposed to just being a data index object with a specific name? Is it only to make the event callback invocation tidy?

**Comment by BenKnorlein** [comment]
Yeah. You are right. We do not gain much from Subclassing, when there is no additional functionality in  the VREvent as we do not use the constructor of the Subclass at that level, but maybe we would like to add some at a later stage of MinVR2. we could also have an extra mechanism at a higher level, e.g. a high-level device/plugin/module could register a VREvent factory to create its specific event. 

I think if we do not provide the base (a VREvent) now, the design and usage will have to change a lot if we like to use specific events on a higher level. If we use them now, it will provide us more functionality and more compatibility between low and high level. In additon, we could subclass using a Decorator pattern to provide addtional functionality which would not require calling the specialized constructor in the beginning.

Finally i also still think that the other points are also valid: Deletion, handling in an Eventqueue etc becomes more clear and easy to handle. And for me both values, name and data should not be separable.

**Comment by dankeefe** [comment]
Edit:  I was just about to post the message below when I saw Ben's most recent post come in at the same time... so some of this repeats what he just said...  I guess I'll post anyway as it might be useful to see in different wording.  Check out the idea at the end about "MaxVR" --- that's probably the most relevant point from my post now :)

....

I like the possibility of what Ben describes, but for the reasons Tom describes I don't think it actually requires a base VREvent class inside of MinVR.  It could work that way, and I think the major benefit would be keeping things clean and making sure that the event name and event data are always accessible together in the same object.

Ben, when you say, "When the Joystick receives a VREvent which was assigned to him, the joystick can cast it as a VRJoystickEvent and run its own callback."  I think that this would not actually be a casting operation.  Casting would require that the VREvent was created as a VRJoystickEvent in the first place inside MinVR.  We could implement that, but then we would need to modify MinVR every time a new event type is added -- one of the things we wanted to avoid in the original design.

Instead what I imagine is that you would have a JoystickEventGenerator or JoystickModule or something like that register itself with MinVR's generic event callback and then it would listen for all "events" that come out of MinVR, look at event name for each one, figure out if it makes sense to treat as a JoystickEvent, and if it does then create a new JoystickEvent at that time.  Programmers could then register a joystick-specific JoystickEvent callback with the JoystickModule. In this approach, JoystickEvent, JoystickModule, and everything else that relates to joystick could be pretty easily separated from the core of MinVR.  

BIGGER SUGGESTION:  What this suggest to me at the higher level is:  MaxVR!  Maybe we should start work at the same time on a sister project, "MaxVR", that includes ideas that we want to support but that would lie beyond the scope of MinVR.  For example, I think of MinVR as being the "glut" of VR toolkits -- super flexible, but not really the tool that you want to build a major application on top of.  Sometimes, this is all you want -- keep it simple and create a quick program, or easily adapt some existing 3D graphics program to VR.  But, if you are creating a really serious program, like CavePainting or some major new SciVis tool, you don't want to work directly with glut or MinVR, you want a few more tools, like some layer on top that can help you build a robust application.  In VRG3D, the "vrbase" subdirectory helps with this and includes some file input/output for 3D models and FSA's and other structures to handle events in a way that goes beyond the simple long "if statement" that is used in a simple program, like vrg3d_demo.  For MinVR, I can imagine a library called MaxVR that sits on top and has a full event system that defines a VREvent base class and then a series of subclasses, maybe some templates for state machines, some tools to build 3D menu systems, etc.

**Comment by tsgouros** [comment]
+1 to the idea of MaxVR. Not that I want to write that (you can!), but that I think it is useful to think of MinVR as being the minimum structure necessary to implement a MaxVR, but also useful in a wide variety of other VR applications, of a variety of different scales. Wherever we have a design decision to make, I think we should choose the less restrictive option, and let the restrictions come from the designs on top of it that we facilitate.

**Comment by BenKnorlein** [comment]
@Dan : I like the idea of a higher level functionality and was thinking that the original idea was going there anyways. However, I am not sure if it should be one big library or MinVR with different Modules on top of it. E.g. If i only want to do loading of meshes i do not want to have to provide support for videos as this could lead to many additional libraries which have to be integrated. So i think a modular design would be more flexible. This would be also be possible in a comfortable way by using cmake and a FindMinVR.cmake script in which different components can be loaded similar to QT, e.g. find_package(MinVR core vrpn video meshes) or built by using cmake flags

@Tom : I am not sure what you mean with the less restrictive option? For me it is less restrictive to have VREvents as it would not restrict high level abstractions and does still support all basic ideas and the flexibility of MinVR.

And the more i think about it, the more i think we should use proper Software Design patterns for the MinVR base. I think this really facilitates adding additional; functionalities and abstractions for the higher level without breaking the base or without being completely different to the core MinVR. For me the goal of MinVR should be that it is minimal (to learn and to use) when a developer wants to use it as a library, this does for me not necessarily mean that MinVR itself should be written as minimal as possible, but maybe i am wrong there. It would be interesting to see what you all think. (I also do not want to overly complicate the design, but some patterns can provide a lot of flexibility later on)

E.g.For the example of Events i could see the following workflow in MinVR:
- name and VRIndex are received 
- Both are combined in a VREventFactory to a VREvent https://en.wikipedia.org/wiki/Factory_method_pattern
- The Event is then added to the Queue (FIFO)
- The Queue is processed by the callbacks when the user triggers it. The Events are directly deleted after processing and remove from the Queue

The idea of the Factory would be to either allow on a higher Level specialized Factories by subclassing or it would also be possible to register additional VREventFactories to a VREventFactory to create subclasses of VREvents.

I know that we will not use this in MinVR, but i think if we do not implement basic mechanism like this at the base that it will be extremely difficult to provide this at a higher level without having to change and redo things a lot. In addition I do not see much additional complexity with this but the design patterns make it even cleaner for me.

**Comment by tsgouros** [comment]
A few points:
1. You don't have to go to Wikipedia for factories.  There is an example of the factory pattern in the config directory, where it is used by the dataIndex to accommodate the different data types supported there.
2. A factory is a nice way to abstract the issues of varying types, but under the covers it's really the same as the big if statement that you said you wanted to avoid.  The one in config is hidden in a std::map, but that's just a moderately slick way to implement a switch{} statement. (And the slickness is completely undone by the impossibility of initializing a static std::map in C++.)
3. If the MinVR apparatus does not need to know about this (and I believe it does not) then why force it on the user?  Let's include a factory in our example event callback, and won't that be enough.  The point of MinVR is to be the smallest possible, right?  So let the various responsibilities fall where they can be dealt with.  The callbacks can't know about the network communication or the order of the events, so let MinVR deal with the queueing and get the event data in the right order to pass in to the callbacks, and let the callbacks do what they will with it.  If that means creating a class and a factory and all, fine, whatever.  But what the data is, or how to process it, let that remain the province of the callback developer.  Same in reverse: let MinVR remain ignorant of the graphics and implementation details.
4. The question to ask about any potential MinVR feature or requirement is whether it adds value to the programmer who is going to adapt their program to use it.  My contention isn't that a VREvent is a bad idea in itself, only that it's a good idea -- for the callback developer to implement.
5. There is some detail missing from our conception of the example program.  In between the synchronizeAndProcessEvents call and the renderOnAllDisplayDevices call, the graphics program is going to do something -- draw stuff, process stuff, whatever.  Some of the data it uses in those steps is going to be config data, stored in the main dataIndex.  That is, some of what we are going to tell the programmer adapting their software is to use index->getData("projectorCorners") or something like that instead of a variable called projectorCorners.  That's how to keep all the instances singing from the same music.
6. The callback functions will definitely need access to the dataIndex. My suggestion would be including them in the call sequence rather than making the index into a global variable.
7. If the main data index is in the call to the callback function, then why not include the event data there? As in Dan's example, it would be like this:

```
// Idea 6
// The argument to the callback is the big main index containing everything.
void myEventCallback(std::string eventName, VRDataIndex bigIndex) {
  if (eventName == “Wand_Move”) {
    VRMatrix4 transform = bigIndex.getValue(“/Wand_Move/Transform”);
  }
}
```

I have only understood the objections to that choice to be intuition. My intuition about it is similarly uneasy, but I checked and the std::map thing is more or less supposed to be thread safe, and I can include a semaphore or something to make it so, and work to make the rest solid, too.
1. The whole reason I started down the path of using the same tools for the event data as the config data was to address the problem of keeping all the dataIndex stores synchronized (something I recall discussing early on).  Events will thus serve not only as ways to get data to all the various processes, but to keep them all in sync with each other, too. I thought we wanted a central record of the total state of the system.
2. As far as the timing goes, the queue object that is actually received by the net interface calls has timing information in it that will serve to keep the event objects in order.
3. I'm probably missing something here, but go ahead and reply and let me know where.  Thanks.

**Comment by dankeefe** [comment]
@BenKnorlein - I hear you on the modules rather than a big "MaxVR" -- totally on board with that.

@BenKnorlein - Can you create a sketch or UML diagram or some pseudocode for the event factory idea and maybe draw some boxes around what would be inside MinVR and what would be outside?  This might help to fully understand.  One issue that I'm not sure how best to handle if we were to do something like this would be staying very flexible in terms of the data structures we used for things like Vector3 and Matrix4 etc.  I kind of like the idea behind how these are treated now where we recognized that these types are fundamentally just an array of floats, so when we pass data around in events, that's really all we need to pass.  Then, when you want to use that data, you just unpack it into whatever Vector3 or Matrix4 is convenient for the graphics API you are working with.  For example, in G3D, I'd want my matrices to be CoordinateFrames.  In OpenScenegraph, I would have some other type for matrices that they define, etc..  Would the factory need to know these types up front?  Would the factory be an add-on module to MinVR?  This is intriguing, and I'd like to understand a little more about how it might work.  At the very least we should be sure that whatever we do does not preclude adding on something like this.

@tsgouros I am on the fence right now in terms of Event class or no event class, but I feel quite strongly that if there is no event class, I would like to limit the data that comes into the event callback to only include the data for that particular event.  It would be a great surprise to me as a programmer if I were to receive a callback with additional data.  In an event callback, the job is to respond to a single event, and if I'm seemingly encouraged to access data from prior (or even future) events since this is passed into the function, then I think that this would lead me toward some bad programming practices.  So, I do feel pretty strongly on that one point.

In terms of globally available data indices, I think that we do need a global dataindex of some type to store config data that is read in from files.  I think we're all on board with that.

In terms of storing event data globally, Ben asked early on about the ability to do something simple like just ask MinVR, what's the current position of the head tracker.  A global data index that maintains the current state of the system would be one way to support this, and I would be ok with adding that to VRMain or some similar place.  But, to me, this would be an extra, separate, convenience feature of MinVR.  I would not want to replace the idea of an event-based system with the idea of a state-based globally managed system.  So, it still seems very important to me that the event callback follow the norms and expectations of an event based system, where the callback simply provides access to the details of the event that just happened.

We've also talked about wanting to pass some information on the current rendering state (e.g., which display am I drawing on, which eye am I currently rendering, what is the current projection matrix) into the draw callback.  That could be done either with a global or local data index or with a RenderState class that we define.  It's not essential, but might be nice if whatever we do for the event callback is similar to the draw callback.  So, let's keep that in the back of our minds as well.

**Comment by BenKnorlein** [comment]
I will write some example detailing the idea of the factory. I think we should also talk about it in the next meeting so i will have it done the latest till then. I think for now it does not matter too much as the change probably does not take much.

**Comment by tsgouros** [comment]
@Dan: The two things a callback needs are the data from the event and the data which it will operate on/with. It has to do _something_ with the data in the event. What does the callback do if it doesn't set some variable or another?  

It's ok with me if the data the callback operates on/with is some set of global variables. But I think it's better if it operates on a global data index. And I think it's in some ways even better if the "global" data is actually a pointer to a big data index explicitly passed into the callback and isn't actually a global variable at all. Didn't you object to globals last time we talked?

I am completely in agreement about wanting this to be an event-based system, where the callback simply provides access to the details of the event that just happened. But what does it do with that event? Being event-based doesn't mean you can't keep track of the state, only that the events cause the state changes. (As opposed to having code that queries for state changes.) Maybe I'm misunderstanding something, but I'm not sure I see the issue that concerns you here.

**Comment by dankeefe** [comment]
The main point on this thread for me is simply to make the MinVR API as easy to understand as possible.  My expectation based on every event-based system I have ever used is that when I get an event callback, it will contain data for that event that is easy for me to access.  If it also contains data for past events, then this has potential to be confusing, and even more so if these data are accessible through the same data structure.  I would think:  This is different than I expected.  Why is the event callback passing me all this data?  Am I supposed to respond to all of the events here or just to the current one?  How am I supposed to use the event callback function in MinVR?  How often is it called?  

For this reason, I'm thinking the best is to keep it simple, and if I wanted to access broader state information about the VR system, then do this through some interface that makes it very clear what is being accessed, for example, a function like VRMain::instance()->getVRState();  

I think I could be talked into something that would instead pass the state into the callback if it were exceedingly clear to the programmer what data are part of the event and what are part of the larger state info.  What if we were to combine the ideas discussed so far into something like the following, where there is a real VREvent class and a separate VRDataIndex for state info -- best of both worlds?

```
/// Idea 7:
void myEventCallback(VREvent *event, VRDataIndex *vrState) {
  if (event->getName() == “Wand_Move”) {
    VRMatrix4 transform = event->getData(“Transform”);
  }
}
```

**Comment by tsgouros** [comment]
I think I must be having a hard time expressing myself, because that's
pretty much what I'm suggesting. The only difference I see between what you
say here is that I am also questioning the value of the C++ event class
definition. (And I'm not even really questioning that, only whether it's
important to have it be at the MinVR level, or leave it to the callback
implementer.) Event callbacks should only be handed one event at a time.
The dequeueing of event information should happen at a higher level in
order not to confuse the callback.

**Comment by dankeefe** [comment]
Let's see what Ben and the others think as well.  I think there is a big difference comparing ideas 6 and 7.  In 7, I'm hoping that the use of an Event class makes it even more clear to the programmer that the event class is the place to access the event name and the event data.  I think that 90% of the time, the programmer will only use the Event class and may not even use the vrState variable.  But, hopefully he/she would not be confused by it being there because it is clearly labeled "vrState" rather than "eventData".  Whereas in idea 6, the typical practice would be that the programmer would access the event data from _the same_ data structure that contains data for all sorts of other events and system information.  I think that has great potential for confusion.

**Comment by tsgouros** [comment]
Closing this because most of the issues seems to have been discussed adequately. Someone can reopen if they want.
