### ISSUE TITLE
No idea how to configure plugins

### ISSUE THREAD

**Issue by tsgouros** [ivlab/MinVR2#26]
Where can we learn how to configure the plugin framework? Spent the morning on this, but don't know how to configure the system to use my own monitor for a display. What is the "command line display" meant to encapsulate? Please provide examples, instructions, comments in the code. Thanks.

**Comment by dankeefe** [comment]
I haven't had a chance to try any of this yet, but I did see that there are some instructions in the README file for how to run an example program with different displays.  Did you look at the README that pops up on the main github page and the example of running with an xml file that creates a GLFW window on the desktop?

In our meeting this week, let's try to do a status update on the main branch.  I'm all for the idea that the code in master should have examples, instructions, and comments, but I know that I haven't done that for any of the net or other stuff I have written in master.  I think that everybody is still catching up.  I think the testing framework should be the next thing that we work on.

**Comment by tsgouros** [comment]
Fair enough. I was starting in on converting my adapted.cpp to a test for many net clients. But I'll make tests for VRDataIndex memory usage instead. But there are no comments in this code, except for the copyright statements. I have no idea what the pieces are for.  VRTimer?

**Comment by dtorban** [comment]
There was quite a bit of documentation in the README.md file on how to get
the plugins working as well as some test examples.  Please referer to the
following for documentation for an example program:

https://github.com/ivlab/MinVR2/blob/master/apps/example/main.cpp

Thanks,
Dan

**Comment by dtorban** [comment]
I want to apologize for the lack of comments on the plugin system.  I
figured I would get to it soon, but wanted to check in what I had.  I
thought that was the plan, for us to just check in what we had.  Also, I
tend to like code that comments itself by names and names of functions,
rather than comments that say what the code says.  A VRTimer is essentially
an abstracted timer that has one method that says getTime().  I needed it
to abstract out glfwGetTime for one of my tests, though I was thinking of
getting rid of it anyhow, which is the reason I didn't care so much.  Also,
it wasn't a strong dependency anywhere.

The plugin framework may not be perfect, but it works at least :).  I think
it is a good start.

Everything should come along in time, but I imagine not everything is
always going to be pristine in our codebase, especially as we are starting
and all committing to the same codebase at the same time.  Someday I hope
that will be true.  I'll try to comment more.

Thanks,
Dan

**Comment by dtorban** [comment]
I also sent quite a number of emails telling how to configure plugins.  Please refer to the emails and the README file.
