### ISSUE TITLE
Events are lost in VRDataQueue

### ISSUE THREAD

**Issue by dtorban** [ivlab/MinVR2#89]
Some events are lost in the VRDataQueue.  I believe this is due to the fact that there is a map in VRDataQueue which maps timestep to serialized object.  If the timestep is same, the new event will override the old.

I was testing with GLFW events, but was experiencing the same thing with head tracking events from VRPN.  Here is the frame output of my test (from just moving the mouse around and clicking):

```
Num events from GLFW: 30
Num Events from data queue: 9
Num events from GLFW: 53
Num Events from data queue: 9
Num events from GLFW: 36
Num Events from data queue: 7
Num events from GLFW: 23
Num Events from data queue: 5
Num events from GLFW: 57
Num Events from data queue: 11
Num events from GLFW: 4
Num Events from data queue: 2
Num events from GLFW: 1
Num Events from data queue: 1
```

Here is how to reproduce the problem:
 1. In SimpleOpenGL example, add a sleep for a second or so inside the render method.
 2. Measure the number of number of events before adding them to the VRDataQueue (i.e. in the VRGLFWInputDevice::appendNewInputEventsSinceLastCall() method in the GLFW plugin).
 3. Measure the number of events coming from the VRDataQueue (i.e. in the VRMain::synchronizeAndProcessEvents() method).

Possible fixes:
 * Append events in map rather than replacing events.
 * Perhaps sort events rather than using a map.
 * Get rid of synchronized events (assume you are receiving them in the correct order).

**Comment by dtorban** [comment]
Here is where I believe the problem is (in [VRDataQueue](https://github.com/MinVR/MinVR/blob/master/src/config/VRDataQueue.cpp)):

```c++
void VRDataQueue::push(const VRDataQueue::serialData serializedData) {

#ifdef WIN32
	LARGE_INTEGER frequency;        // ticks per second
	LARGE_INTEGER t1;
	QueryPerformanceFrequency(&frequency);

	// start timer
	QueryPerformanceCounter(&t1);

	long long timeStamp = (t1.QuadPart) * 1000.0 / frequency.QuadPart + clock();;
#else

  struct timeval tp;
  gettimeofday(&tp, NULL);
  
  // Get current timestamp in milliseconds.
  long long timeStamp = (long long) tp.tv_sec * 1000000L + tp.tv_usec;

#endif

  push(timeStamp, serializedData);
}

void VRDataQueue::push(const long long timeStamp,
                       const VRDataQueue::serialData serializedData) {

  dataMap.insert(std::pair<long long,VRDataQueue::serialData>(timeStamp, serializedData));
}
```

Notice that events with the same time step will overwrite each other.

**Comment by tsgouros** [comment]
Hi Dan:

Another solution would be to look into improving the resolution of the timer on the hardware that is giving the problem. I just used gettimeofday as a hack, and hoped for the best. On Macs and Linux, that has about 10uS resolution and that seems adequate to all but guarantee unique time stamps. 

Unfortunately, I only have Mac and Linux systems to work on, and know nothing useful about developing on Windows in any event. If you're seeing 9 events instead of 53, that sounds like getting the same timestamp is way more probable than I'd expected it would be. Google tells me there is some Windows hardware that just doesn't support a higher-resolution time stamp through QueryPerformance calls. I guess what I'm saying here is that I'll need some help coming up with a way to do a high resolution time stamp in Windows.

Googling found me a couple of interesting ways to attempt a solution. I'll try one of those and maybe you can see if it works on Windows?

**Comment by tsgouros** [comment]
p.s. The reason I used a time stamp instead of just appending the events in order was to make sure that events that come from different sources get properly. The addSerializedQueue() method will take event messages from multiple sources and allow the queue object to present them to the owning program in more or less the right time order, assuming the time stamps will help.

**Comment by dtorban** [comment]
Hey Tom,

I am using linux, not Windows.  The problem still happens. I think perhaps
It would be better to avoid solutions that rely on architecture precision
as some of the systems being used may be quite diverse.

Thanks,
Dan

**Comment by dtorban** [comment]
Yes, I think it is good to try to sort events by time step from different
sources.  It is a good idea.

**Comment by dankeefe** [comment]
Seems like the most robust solution would be to just put events with the same timestep next to each other in the sorted list rather than dropping duplicates?  

Issue #76 relates to this, so it might be worth taking it into account while working on a fix for this.  The problem is that there is a performance hit with serializing events on platforms that do not require you to use network based synchronization.  Whereas the YURT will require lots of synchronization over the network, our Cave and most of the other platforms in our lab do not.  It would be better if events are only serialized when it is necessary to pass them over a network.  I mention this here because I think the queue that does the sorting (discussed in this thread) is the thing that requires the events to be added in a serialized form.

**Comment by tsgouros** [comment]
In this scenario, would the sender and receiver be separate processes, separate threads, or all on one? Are you asking for a heterogeneous kind of receiver that could accept from anyone, or is it either network-aware or not?

**Comment by dankeefe** [comment]
Everything in the same process.  Events read from input devices (potentially in its own thread) and then graphics displayed based on these events in the same application process.

**Comment by tsgouros** [comment]
Hi DanO:

The linux boxes I have access to are down until Wednesday while the CCV tech guys do some maintenance stuff. On my mac, I followed your directions but I can't reproduce the error. The _events.size() in VRGLFWInputDevice::appendNewInputEventsSinceLastCall()  and the queue size in VRMain::synchronizeAndProcessEvents() are always the same for me. I'll assume this is just a hardware thing and see about trying to add a second field to the time-stamp key, but just to be sure, am I looking at the right thing? Can you be more specific about the mods you described up there? Maybe send me a diff of the files involved?

Thanks,

 -Tom

**Comment by tsgouros** [comment]
There is a version of the data queue checked into the beta branch that adds a modifier to the stored timestamp. It should accommodate up to 1000 duplicate timestamps. If you have more than that, good luck.

Unfortunately, I have no way to test right now, because I don't see this problem on the machine I have to test on, probably partly because I have no source of interrupts that comes fast enough. So someone please test for me. I will leave this open until I hear something about the test.

Affected files:

src/config/VRDataQueue.h
src/config/VRDataQueue.cpp
tests/config/CMakeLists.txt
tests/config/queuetest.cpp

**Comment by tsgouros** [comment]
DanK: See issue #41 for further discussion about the non-serializing issue.

**Comment by dtorban** [comment]
Hey Tom, your changes look good.  Hopefully I can get around to testing it soon.  1000 duplicates should be fine I would think.  Thanks so much for making this change.

**Comment by dtorban** [comment]
By the way, in the future, please submit a pull request to the beta branch.  That way I could test it before it is merged.  For example, perhaps it doesn't work and you needed to take another approach.

**Comment by tsgouros** [comment]
Do you have results for this? I'd like to close it.

**Comment by dtorban** [comment]
I haven't had time to test yet, but I might get around to it today or in
the next week.

**Comment by dtorban** [comment]
Just tested.  Works great!  Thanks Tom :).  Closing.
